# raise lançamdp exceções (erros)

print(123)
raise ValueError('Deu erro')
print(456)
